version: '3.8'

services:
  node:
    build: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/backend/:/usr/src/app/
    expose:
      - 5000

    env_file:
      - ./.env.prod


  nginx-manager:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.manager

    ports:
      - 1337:80
  
  nginx-node:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.node
    
    ports:
      - 1337:80