version: '3.8'

services:
  backend-node:
    build: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5555:5000

    restart: always

    env_file:
      - ./.env.prod
    
    volumes:
      - ./media:/usr/src/app/media
  
  frontend:
    container_name: frontend
    build:
        context: ./services/frontend
        dockerfile: Dockerfile
    
    restart: always
    
    ports:
        - "3877:3876"
    

  file-manager:
    build: ./services/file-manager
    command: python FileManager.py

    env_file:
      - ./.env.prod
    
    restart: always
    
    volumes:
      - ./media:/usr/src/app/media

  redis-manager:
    image: redis:6.2-alpine
    hostname: redis
    restart: always
    volumes:
      - ./services/redis/data:/data
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    env_file:
      - ./.env.prod



# docker pull nginxinc/amplify-agent
