version: '3.8'

services:
  manager:
    build: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/backend/:/usr/src/app/
    expose:
      - 5000

    env_file:
      - ./.env.prod
    
    environment:
    - IP=127.0.0.1
  
  node-1:
    build: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/backend/:/usr/src/app/
    expose:
      - 5000

    env_file:
      - ./.env.prod
    
    environment:
      - IP=127.0.0.1
  
  nginx:
    build: ./services/nginx
    
    ports:
      - 1337:80

    depends_on:
      - web