version: '3.8'

services:
  backend-node:
    build: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    # expose:
    #   - 5000
    ports:
      - 5000:5000

    env_file:
      - ./.env.prod
    
    volumes:
      - ./media:/usr/src/app/media
  
  frontend:
    container_name: frontend
    build:
        context: ./services/frontend
        dockerfile: Dockerfile
    
    ports:
        - "3876:3000"
    

  file-manager:
    build: ./services/file-manager
    command: python FileManager.py

    env_file:
      - ./.env.prod
    
    volumes:
      - ./media:/usr/src/app/media

  backend-manager:
    build: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    # expose:
    #   - 5000
    ports:
      - 5000:5000

    env_file:
      - ./.env.prod
    
    volumes:
      - ./media:/usr/src/app/media


  nginx-manager:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.manager

    ports:
      - 1337:80
    
    volumes:
      - ./media:/home/app/web/media
  
  nginx-node:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.node
    
    ports:
      - 80:80
    
    volumes:
      - ./media:/home/app/web/media

  redis-manager:
    image: redis:6.2-alpine
    hostname: redis
    volumes:
      - ./services/redis/data:/data
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    env_file:
      - ./.env.prod
  
  amplify:
    image: "nginxinc/amplify-agent"
    environment:
      - API_KEY=540b099db29073cd8ed91f97c0078087
      - AMPLIFY_IMAGENAME=youtube
  
  memcached:
    container_name: memcached
    
    image: memcached:latest
    
    restart: always
    
    ports:
        - 11211
  
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${IP}
      - SUBDOMAINS=wildcard,
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      - DHLEVEL=4096
    volumes:
      - ./services/nginx/config:/config
    restart: unless-stopped



# docker pull nginxinc/amplify-agent
