version: '3.8'

services:
  node:
    build: ./services/backend
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    # expose:
    #   - 5000
    ports:
      - 6001:5000

    env_file:
      - ./.env.prod
    
    volumes:
      - ./media:/usr/src/app/media


  nginx-manager:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.manager

    ports:
      - 1337:80
    
    volumes:
      - ./media:/home/app/web/media
  
  nginx-node:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile.node
    
    ports:
      - 1337:80

    
    volumes:
      - ./media:/home/app/web/media

  redis:
    image: "redis:alpine"
    hostname: redis
    volumes:
      - ./services/redis/data:/data
  
  amplify:
    image: "nginxinc/amplify-agent"
    environment:
      - API_KEY=540b099db29073cd8ed91f97c0078087
      - AMPLIFY_IMAGENAME=youtube
# docker pull nginxinc/amplify-agent
